- context.go
- maniphttp/manipulator.go
- maniphttp/manipulator_test.go
- options.go
- options_test.go
This PR allows callers to provide an API token per call and override the default API token that is resolved in the manipulator. This allows the manipulator to make calls on behalf of other users.
> Allow per-context delegation token override

- manipmemory/manipulator.go
- manipvortex/manipulator.go
this patches fixes a dead lock when Flush is called while the manipulator has a prefetcher
> fixed: deadlock in flush

- maniphttp/manipulator.go
- maniphttp/manipulator_test.go
This patch should fix the case where send
function can return a nil error and a nil
response when retrying auth auth is while the context just got expired.
> fixed: panic in certain circumstances

- maniphttp/manipulator.go
- maniphttp/manipulator_test.go
- maniphttp/options.go
- maniphttp/options_test.go
This patch adds the option OptionSimulateFailures to inject random failure in the low level communication process.
> new/maniphttp: add option to simulate failure

- maniphttp/manipulator.go
- maniphttp/manipulator_test.go
The retry logic will essentially retry for ever if it is forbidden/unauthorized. It will renew the token and jump to retry that will start everything again. 
The change limits the number of retry attempt to a maximum of 2.
> Fix the manipulator retries on forbidden/unauthorized

- manipvortex/manipulator.go
Fixes the crash in vortex manipulator where it was assuming that the filter is always not nil.
> Fix crash in vortex subscriber when there is no filter

- maniphttp/manipulator.go
This PR will aim to fix the following data race:
```
==================
WARNING: DATA RACE
Read at 0x00c0027b1710 by goroutine 227:
bytes.(*Buffer).Read()
/usr/local/go/src/bytes/buffer.go:72 +0x60
io/ioutil.(*nopCloser).Read()
<autogenerated>:1 +0x87
net/http.transferBodyReader.Read()
/usr/local/go/src/net/http/transfer.go:62 +0x77
io.(*LimitedReader).Read()
/usr/local/go/src/io/io.go:448 +0xc7
bufio.(*Writer).ReadFrom()
/usr/local/go/src/bufio/bufio.go:722 +0x13b
io.copyBuffer()
/usr/local/go/src/io/io.go:388 +0x3fa
net/http.(*transferWriter).writeBody()
/usr/local/go/src/io/io.go:364 +0xc3f
net/http.(*Request).write()
/usr/local/go/src/net/http/request.go:655 +0x85e
net/http.(*persistConn).writeLoop()
/usr/local/go/src/net/http/transport.go:1979 +0x321
Previous write at 0x00c0027b1710 …
```
> Fixed: remove race around bodyCloser when no content

- context.go
- context_test.go
- maniphttp/options_test.go
- manipmongo/manipulator.go
- manipmongo/options.go
- manipmongo/options_test.go
- options.go
- options_test.go
This patch allows manipulator implementations to enhance the context by providing additional options specific to that implementation.
> new: added opaque data in manipulate.Context

- internal/push/push.go
- internal/push/utils.go
- internal/push/utils_test.go
- maniphttp/manipulator.go
- maniphttp/options.go
- maniphttp/options_test.go
- maniphttp/subscriber.go
- maniphttp/subscriber_test.go
This patch provides the following changes:
- added option `maniphttp.OptionSendCredentialsAsCookie("key")` which will send the password in a cookie with the provided key instead of Authorization header when using http manipulator
- added option `maniphttp.SubscriberSendCredentialsAsCookie("key")` which will send the password in a cookie with the provided key instead of token parameter when connecting to the push channel
> new: added options to maniphttp manipulator and subscriber to pass credential as a cookie

- maniphttp/manipulator.go
I believe the root cause of the flakiness is because the last status from the server is being overwritten in the event of a retry that resulted in the request context exceeding its deadline (_or a network error_). See:
• https://github.com/aporeto-inc/manipulate/blob/master/maniphttp/manipulator.go#L670
• https://github.com/aporeto-inc/manipulate/blob/master/maniphttp/manipulator.go#L678
Instead, what I believe it should do is only assign the `NewErrCannotCommunicate` to `lastError` IFF `lastError != nil` because there could have been a connection to the server which failed due to any of the following HTTP status codes: https://github.com/aporeto-inc/manipulate/blob/master/maniphttp/manipulator.go#L696-L719
The tests are failing because the last status is sometimes thrown away if there …
> fix: do not overwrite last error if it was previously set - fixes flaky tests

- internal/backoff/backoff.go
- internal/backoff/backoff_test.go
- maniphttp/manipulator.go
This PR fix the following:
- in the backoff Next, if the deadline is expired, do not return a negative wait duration
- in manipulate http, correctly close the response body so keep alive is used (Avoid to do new TLS handshake in case of retries)
> Fixes on Manipulate http and backoff

- internal/push/push.go
- internal/push/utils.go
- internal/push/utils_test.go
- maniphttp/manipulator_test.go
- maniphttp/subscriber.go
- maniphttp/subscriber_test.go
addresses: https://github.com/aporeto-inc/aporeto/issues/2500
- Should we add new event types to indicate that the client is now in an error state and/or leaving an error state?
✅ Unit tests
> new: add support for handling websocket error events

- manipmongo/helpers.go
- manipmongo/helpers_test.go
- manipmongo/internal/compiler/filter.go
- manipmongo/internal/compiler/filter_test.go
- manipmongo/manipulator.go
- manipmongo/options.go
- manipmongo/options_test.go
- manipmongo/sharder.go
- manipmongo/utils.go
- manipmongo/utils_test.go
Previously, we were using bson.M which was not preserverving the order, ending up with filters that could bypass indexing.
> fixed: use bson.D for filters instead of bson.M

- manipmongo/helpers.go
- manipmongo/helpers_test.go
- manipmongo/internal/compiler/filter.go
- manipmongo/internal/compiler/filter_test.go
- manipmongo/manipulator.go
- manipmongo/options.go
- manipmongo/options_test.go
- manipmongo/sharder.go
- manipmongo/utils.go
- manipmongo/utils_test.go
Previously, we were using bson.M which was not preserving the order, ending up with filters that could bypass indexing.
> fixed: use bson.D for filters instead of bson.M (#119)

- go.mod
- go.sum
- maniphttp/internal/syscall/syscall_linux.go
- maniphttp/internal/syscall/syscall_nonlinux.go
- maniphttp/manipulator.go
- maniphttp/manipulator_test.go
- maniphttp/options.go
- maniphttp/options_test.go
- maniphttp/utils.go
Issue: Whenever the network connection dies after the handshake, the TCP doesn't kill the connection until it times out, it starts the re-transmission timer and keeps up retrying the packets which leads to the socket buffer being full and wastage of resources. This will happen till TCP timeouts saying there is no ACK far any of the packets, which is default by 15-30 mins, depends on the OS. 
This was observed in one of the Openshift issue: https://github.com/aporeto-inc/aporeto-devs/issues/528
We are still debugging why is the pre-existing connections dropped by eBPF but for now this 
Fix: Add a TCP socket option.
I think this should be always there. Even the golang grpc has this by default.
> ManipHttp: Add client TCP_USERTIMEOUT option to the socket.

- maniphttp/backoff.go
- maniphttp/manipulator.go
- maniphttp/manipulator_test.go
This is an attempt to trap the tcp close we can have in case of tcp rate limiting.
As we are trying to optimize the rate limiting at the gateway level, upon tcp closing, the `syscall.ECONNRESET` as a net.OpError is raised(`connection reset by peer`). We are intercepting that event to move the retry to the strong retry curve.
> impr/maniphttp: Retry in case of broken pipe, reset by peer

- maniphttp/manipulator.go
- maniphttp/manipulator_test.go
This patch fixes the handling of `context.Canceled` in maniphttp. It is now returning a `manipulate.ErrDisconnected` that was designed for this, but was never used.
> fixed: context.Canceled should use ErrDisconected

- errors.go
- errors_test.go
- internal/push/utils.go
- maniphttp/manipulator.go
- maniphttp/manipulator_test.go
- maniphttp/options.go
- maniphttp/utils.go
- manipmemory/manipulator.go
- manipmongo/helpers.go
- manipmongo/manipulator.go
- manipmongo/utils.go
- manipmongo/utils_test.go
- manipvortex/manipulator_test.go
This patch improve the old manipulate.Error to support error wrapping. Old methods have been deprecated
> new: start migration to support error wrapping

- errors.go
- manipmongo/utils.go
- manipmongo/utils_test.go
https://redlock.atlassian.net/browse/CNS-1927
Add new error handling logic so we can catch query errors that were due to the client. This will allow us to return appropriate status codes in the backend.
> CNS-1972: catch query errors that were due to the client

- maniphttp/helpers.go
- maniphttp/helpers_test.go
This patch adds the ExtractTransport helper to retrieve the http.Transport used by the given HTTP manipulator.
> new/maniphttp: added ExtractTransport helper

- maniphttp/manipulator.go
- manipulate.go
A SelfTokenManager is a TokenManager with SetManipulator as
an additional method. This methiod will be called before the
token manager is used.
This can be useful when you can use the current manipulator
to renew tokens.
> new: add SelfTokenManager interface

- manipmongo/manipulator.go
> fixed: correctly translate namespace key when using ctx.Namespace()

- manipmongo/manipulator.go
- manipmongo/utils.go
- manipmongo/utils_test.go
This patch adds a better error management when manipmongo calls q.SetMaxTime, by verifying that the given context is not in error. If so, returns a manipulate.ErrCannotBuildQuery wrapping the error.
> fixed/manipmongo: error handling for setMaxTime

- .github/workflows/build-go.yaml
- manipmongo/manipulator.go
We are operating at a much higher scale today than couple of years back, and I don't think 60sec timeout plays well with our 71mil resource scale for example. We started seeing more timeouts after mongo-go-driver changes as those might have pushed us beyond the edge.
Doubling the timeout.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
> bumping up default context timeout in manipmongo from 1min to 2 mins
